import { StyleSheet } from "react-native";

export const workoutsStyle = StyleSheet.create({
  title: {
    textAlign: "center",
    fontSize: 30,
    fontStyle: "normal",
    fontWeight: "bold",
    lineHeight: 38,
    letterSpacing: 0.3,
    color: "#FFF",
    width: 300,
  },
  subtitle: {
    textAlign: "center",
    fontSize: 16,
    fontStyle: "normal",

    // lineHeight: "160%",
    letterSpacing: -0.4,
    color: "#D7D8D9",
    width: 300,
    marginTop: 12,
    marginBottom: 37,
  },

  card: {
    width: 105,
    height: 105,
    borderRadius: 14,
    backgroundColor: "#24262B",
    margin: 5,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  cardDisabled: {
    width: 105,
    height: 105,
    borderRadius: 14,
    backgroundColor: "#3b3c3d",
    margin: 5,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  cardSelected: {
    width: 105,
    height: 105,
    borderRadius: 14,
    backgroundColor: "#FF8036",
    margin: 5,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  cardText: {
    textAlign: "center",
    fontSize: 16,
    fontStyle: "normal",

    // lineHeight: "160%",
    letterSpacing: -0.4,
    color: "#FFF",
    marginTop: 11,
  },
  cardTextDisabled: {
    textAlign: "center",
    fontSize: 16,
    fontStyle: "normal",

    // lineHeight: "160%",
    letterSpacing: -0.4,
    color: "#c9c9c9",
    marginTop: 11,
  },
  startButton: {
    width: 305,
    height: 54,
    borderRadius: 12,
    backgroundColor: "#FF8036",
    marginTop: 24,
    justifyContent: "center",
    alignItems: "center",
  },
});
