import { StyleSheet } from "react-native";

export const homeStyles = StyleSheet.create({
  home_1: {
    date: {
      color: "#6b7280",
      fontSize: "12px",
      fontStyle: "normal",
      fontWeight: 400,
      lineHeight: 20,
      letterSpacing: 0.3,
    },
    welcome: {
      color: "#FFF",
      fontSize: "16px",
      fontStyle: "normal",
      fontWeight: 600,
      lineHeight: 20,
      letterSpacing: "0.2px",
    },
    caloriesTitle: {
      color: "#FFF",
      fontSize: "14px",
      fontStyle: "normal",
      fontWeight: 600,
      lineHeight: 20,
      letterSpacing: "0.2px",
    },
    caloriesDates: {
      color: "#6b7280",
      fontSize: "12px",
      fontStyle: "normal",
      fontWeight: 400,
      lineHeight: 20,
      letterSpacing: 0.3,
      paddingTop: "4px",
    },
  },
  home_2: {
    imageCard: {
      card: {
        width: 303,
        height: 166,
        borderRadius: 12,
        border: "1px solid #37383C",
        overflow: "hidden",
      },
      cardAll: {
        width: "100%",
        marginRight: "24px",
        height: 166,
        borderRadius: 12,
        border: "1px solid #37383C",
        overflow: "hidden",
      },
      title: {
        color: "#FFF",
        fontSize: 20,
        fontStyle: "normal",
        fontWeight: 700,
        lineHeight: "120%",
        marginBottom: 14,
      },
      category: {
        color: "#FFF",
        fontSize: 12,
        fontStyle: "normal",
        fontWeight: 500,
        lineHeight: "170%",
        letterSpacing: 0.3,
        marginBottom: 10,
      },
      button: {
        display: "flex",
        width: 111,
        height: 32,
        padding: "8px 16px",
        justifyContent: "center",
        alignItems: "center",
        gap: 8,
        borderRadius: 8,
        background: "#FF8036",
      },
    },
    seeAll: {
      color: "#FF8036",
      fontSize: "12px",
      fontStyle: "normal",
      fontWeight: 400,
      lineHeight: 20,
      letterSpacing: 0.3,
      marginRight: "24px",
    },
  },
});
